library(MASS)
book_colors_transp <- read.csv("~/Dropbox/docs/A_Song_of_Ice_and_Fire/SIF/book_colors_transp.csv", header=TRUE)
head(book_colors_transp)
df <- data.frame(book_colors_transp$X1, book_colors_transp$X2, book_colors_transp$X3, book_colors_transp$X4, book_colors_transp$X5)
row.names(df) <- abbreviate(book_colors_transp$X, 10, method="both")
names(df) <- abbreviate(c("1", "2", "3", "4", "5"), 10, method="both")
biplot(corresp(df, nf = 2))
dev.off()
png(file="/home/boris/Work/Martin_tutorial/code/colors/biplot.png", width=800 , height=800)
biplot(corresp(df, nf = 2))
dev.off()
