library(MASS)
house_colors_transp <- read.csv("/home/boris/Work/Martin_tutorial/code/colors/house_colors_transp.csv", header=TRUE)
head(house_colors_transp)
df <- data.frame(house_colors_transp$targaryen, house_colors_transp$frey, house_colors_transp$greyjoy, house_colors_transp$stark, house_colors_transp$karstark, house_colors_transp$martell, house_colors_transp$tyrell, house_colors_transp$clegane, house_colors_transp$tully, house_colors_transp$mormont, house_colors_transp$cassel, house_colors_transp$arryn, house_colors_transp$tarly, house_colors_transp$baratheon, house_colors_transp$lannister)
row.names(df) <- abbreviate(house_colors_transp$X, 10, method="both")
names(df) <- abbreviate(c("targaryen", "frey", "greyjoy", "stark", "karstark", "martell", "tyrell", "clegane", "tully", "mormont", "cassel", "arryn", "tarly", "baratheon", "lannister"), 10, method="both")
biplot(corresp(df, nf = 2))
dev.off()
png(file="/home/boris/Work/Martin_tutorial/code/colors/biplot_house.png", width=800 , height=800)
biplot(corresp(df, nf = 2))
dev.off()
