library(MASS)
pers_colors_transp <- read.csv("/home/boris/Work/Martin_tutorial/code/colors/pers_colors_transp.csv", header=TRUE)
head(pers_colors_transp)
df <- data.frame(pers_colors_transp$arya, pers_colors_transp$barristan, pers_colors_transp$beric, pers_colors_transp$bran, pers_colors_transp$bronn, pers_colors_transp$brienne, pers_colors_transp$cersei, pers_colors_transp$craster, pers_colors_transp$daario, pers_colors_transp$daenerys, pers_colors_transp$drogo, pers_colors_transp$eddard, pers_colors_transp$hodor, pers_colors_transp$jaime, pers_colors_transp$joffrey, pers_colors_transp$jorah, pers_colors_transp$melisandre, pers_colors_transp$petyr, pers_colors_transp$rickon, pers_colors_transp$robb, pers_colors_transp$catelyn, pers_colors_transp$sansa, pers_colors_transp$stannis, pers_colors_transp$tyrion, pers_colors_transp$tywin, pers_colors_transp$varys, pers_colors_transp$viserys, pers_colors_transp$ygritte, pers_colors_transp$yoren, pers_colors_transp$davos, pers_colors_transp$margaery)
row.names(df) <- abbreviate(pers_colors_transp$X, 10, method="both")
names(df) <- abbreviate(c("arya", "barristan", "beric", "bran", "bronn", "brienne", "cersei", "craster", "daario", "daenerys", "drogo", "eddard", "hodor", "jaime", "joffrey", "jorah", "melisandre", "petyr", "rickon", "robb", "catelyn", "sansa", "stannis", "tyrion", "tywin", "varys", "viserys", "ygritte", "yoren", "davos", "margaery"), 10, method="both")
biplot(corresp(df, nf = 2))
dev.off()
png(file="/home/boris/Work/Martin_tutorial/code/colors/biplot_house.png", width=1200 , height=1200)
biplot(corresp(df, nf = 2))
dev.off()